version: '3.8'

services:
  property-agent:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: property-scraper-api-dev
    ports:
      - "8000:8000"
    environment:
      - APIFY_TOKEN=${APIFY_TOKEN}
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    env_file:
      - .env
    volumes:
      # Mount source code for live reloading (development only)
      - ./src:/app/src
      - ./api_server.py:/app/api_server.py
      - ./src/run_agent.py:/app/src/run_agent.py
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - property-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 30s
    # Override CMD for development with auto-reload
    command: ["uvicorn", "api_server:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--log-level", "debug", "--access-log"]

networks:
  property-net:
    driver: bridge 